# Generated by Django 3.2.5 on 2021-07-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
